// Mocks generated by Mockito 5.4.6 from annotations
// in currency_converter/test/features/converter/presentation/bloc/converter_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:currency_converter/core/error/failures.dart' as _i7;
import 'package:currency_converter/features/converter/domain/entities/conversion_result.dart'
    as _i8;
import 'package:currency_converter/features/converter/domain/entities/currency_result.dart'
    as _i10;
import 'package:currency_converter/features/converter/domain/repositories/converter_repository.dart'
    as _i2;
import 'package:currency_converter/features/converter/domain/repositories/currency_repository.dart'
    as _i4;
import 'package:currency_converter/features/converter/domain/usecases/convert_currency.dart'
    as _i5;
import 'package:currency_converter/features/converter/domain/usecases/get_currencies.dart'
    as _i9;
import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeConverterRepository_0 extends _i1.SmartFake
    implements _i2.ConverterRepository {
  _FakeConverterRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCurrencyRepository_2 extends _i1.SmartFake
    implements _i4.CurrencyRepository {
  _FakeCurrencyRepository_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ConvertCurrency].
///
/// See the documentation for Mockito's code generation for more information.
class MockConvertCurrency extends _i1.Mock implements _i5.ConvertCurrency {
  MockConvertCurrency() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ConverterRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeConverterRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.ConverterRepository);

  @override
  _i6.Future<_i3.Either<_i7.Failure, _i8.ConversionResult>> call(
    _i5.ConvertCurrencyParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i6.Future<_i3.Either<_i7.Failure, _i8.ConversionResult>>.value(
                  _FakeEither_1<_i7.Failure, _i8.ConversionResult>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i6.Future<_i3.Either<_i7.Failure, _i8.ConversionResult>>);
}

/// A class which mocks [GetCurrencies].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCurrencies extends _i1.Mock implements _i9.GetCurrencies {
  MockGetCurrencies() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.CurrencyRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeCurrencyRepository_2(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i4.CurrencyRepository);

  @override
  _i6.Future<_i3.Either<_i7.Failure, _i10.CurrencyResult>> call(
    _i9.GetCurrenciesParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i6.Future<_i3.Either<_i7.Failure, _i10.CurrencyResult>>.value(
                  _FakeEither_1<_i7.Failure, _i10.CurrencyResult>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i6.Future<_i3.Either<_i7.Failure, _i10.CurrencyResult>>);
}
